Feature/second part of course
ngc6166/go-metrics pull request #6
Opened 2022-06-14 20:55 UTC by ngc6166

2022-06-15 13:32 UTC, rktkov approved these changes

2022-07-13 08:28 UTC, rktkov requested changes

2022-07-13 08:28 UTC, rktkov commented on internal/pkg/probe/sender.go
> +			if err != nil {
Правильно я понимаю, что даже если нам вернулась ошибка кодирования, то в body попытаемся записать nil?

2022-07-13 08:28 UTC, rktkov commented on internal/pkg/security/encryption.go
> +func Encrypt(plaintext []byte, key *rsa.PublicKey) ([]byte, error) {
Что будет если на вход метода интерфейса придет key = nil?

2022-07-13 08:28 UTC, rktkov commented on internal/pkg/monitor/server.go
> +	"go-metrics/internal/pkg/security"
Пакет не в своем блоке

2022-07-13 08:28 UTC, rktkov commented on internal/pkg/monitor/monitor.go
> +	"go-metrics/internal/pkg/logger"
Пакет не в своем блоке

2022-07-13 08:28 UTC, rktkov commented on internal/pkg/monitor/handlers.go
> +	"go-metrics/internal/pkg/security"
Пакет не в своем блоке

2022-07-13 08:28 UTC, rktkov commented on internal/pkg/monitor/server.go
> +		logger.Log.Error("unable to read private key")
Если произошла ошибка, то privateKey = nil. Это ситуация корректно отрабатывается дальше по коду?

2022-07-13 08:28 UTC, rktkov commented on internal/pkg/monitor/server.go
> +	router.POST("/updates/", routeUpdateBatchHandler(storage, privateKey))
Внутренний метод корректно отработает privateKey = nil

2022-07-13 08:28 UTC, rktkov commented on internal/pkg/config/config.go
> +	"go-metrics/internal/pkg/logger"
Пакет не в своем блоке

2022-07-13 11:58 UTC, ngc6166 commented on internal/pkg/probe/sender.go
> +			if err != nil {
Исправил.

2022-07-13 11:58 UTC, ngc6166 commented on internal/pkg/monitor/monitor.go
> +	"go-metrics/internal/pkg/logger"
Исправил.

2022-07-13 11:58 UTC, ngc6166 commented on internal/pkg/config/config.go
> +	"go-metrics/internal/pkg/logger"
Исправил.

2022-07-13 12:03 UTC, ngc6166 commented on internal/pkg/security/encryption.go
> +func Encrypt(plaintext []byte, key *rsa.PublicKey) ([]byte, error) {
Исправил.

2022-07-13 13:10 UTC, ngc6166 commented on internal/pkg/monitor/server.go
> +		logger.Log.Error("unable to read private key")
Исправил.

2022-07-13 13:12 UTC, ngc6166 commented on internal/pkg/monitor/server.go
> +	router.POST("/updates/", routeUpdateBatchHandler(storage, privateKey))
Исправил.

2022-07-14 10:18 UTC, rktkov approved these changes

2022-07-14 11:53 UTC, merged